api/urls.py
from django.urls import path, include, re_path
from api.routers import api_router
from api.views import ChartView

app_name = 'api'

urlpatterns = [
    path('', include(api_router.urls)),
    re_path(r'chart/(?P<from>[\w\-\.]+)/(?P<to>[\w\-\.]+)/$', ChartView.as_view()),
]

app/urls.py
from django.urls import re_path, path

from . import views

app_name = 'app'

urlpatterns = [
    path('cves/list/', views.index, name='index'),
    path('cves/chart/', views.chart, name='chart'),
    re_path(r'cves/detail/(?P<id>[-\w]+)', views.detail, name='detail'),
    re_path(r'cves/download/(?P<id>[-\w]+)', views.download, name='download'),
]

nvd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('api/', include('api.urls')),
    path('', lambda r: redirect('app:index'))
]

app/models.py
from django.db import models


class CVE(models.Model):
    cve_id = models.CharField(primary_key=True, verbose_name="CVE Id", max_length=20)
    summary = models.TextField(verbose_name="Summary")
    published_date = models.DateField("Published Date", blank=True, null=True)
    last_modified_date = models.DateField("Last Modified Date", blank=True, null=True)
    affected_products = models.IntegerField("Number of Affected Products", blank=True, null=True)
    cvss_v2_base_score = models.DecimalField("CVSS V2 Base Score", max_digits=3, decimal_places=1, blank=True, null=True)
    cvss_v2_severity = models.CharField("CVSS V2 Severity", max_length=20, blank=True, null=True)
    cvss_v2_vector_string = models.CharField("CVSS V2 Vector String", max_length=255, blank=True, null=True)
    cvss_v3_base_score = models.DecimalField("CVSS V3 Base Score", max_digits=3, decimal_places=1, blank=True, null=True)
    cvss_v3_severity = models.CharField("CVSS V3 Severity", max_length=20, blank=True, null=True)
    cvss_v3_vector_string = models.CharField("CVSS V3 Vector String", max_length=255, blank=True, null=True)


class AffectedProduct(models.Model):
    id = models.AutoField(primary_key=True)
    cve_id = models.ForeignKey(CVE, on_delete=models.CASCADE)
    vulnerable = models.BooleanField()
    uri = models.CharField("cpe23Uri", max_length=500)


class Reference(models.Model):
    id = models.AutoField(primary_key=True)
    cve_id = models.ForeignKey(CVE, on_delete=models.CASCADE)
    url = models.CharField("URL", max_length=500)
    name = models.CharField("Name", max_length=500)
    source = models.CharField("Ref Source", max_length=20)
    tags = models.CharField("Tags", max_length=255, blank=True, null=True)

api/views.py
from django.shortcuts import render
from django.db.models import Count
from rest_framework import generics
from api.serializers import ChartSerializer
from app.models import CVE


class ChartView(generics.ListAPIView):
    serializer_class = ChartSerializer

    def get_queryset(self):

        from_date = self.kwargs['from']
        to_date = self.kwargs['to']

        if not to_date:
            to_date = from_date

        return CVE.objects.filter(last_modified_date__gte=from_date, last_modified_date__lte=to_date).\
            values('last_modified_date').annotate(cve_count=Count('cve_id')
        )

app/views.py
from django.shortcuts import render
from .models import CVE
from django.core import serializers
from django.http import HttpResponse


def index(request):
    return render(request, 'app/index.html')


def detail(request, id):
    context = {}
    cve = CVE.objects.get(cve_id=id)
    context['cve'] = cve
    return render(request, 'app/detail.html', context)


def download(request, id):
    cve = CVE.objects.get(cve_id=id)
    serialized_cve = serializers.serialize('json', [cve, ])
    response = HttpResponse(serialized_cve, content_type='application/json')
    response['Content-Disposition'] = 'attachment; filename="'+ id +'.json"'
    return response


def chart(request):
    return render(request, 'app/chart.html')

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CVE Lookup</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <style>
        body {
          padding-top: 5rem;
        }
        h3{
            border-bottom: 1px solid lightgray;
        }
        #daterange{
            width: 300px;
        }
    </style>
</head>
<body>
<div>
   <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">CVE Lookup</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:index' %}">CVE List</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'app:chart' %}">Chart</a>
              </li>
            </ul>
          </div>
   </nav>
   {% block main %}{% endblock %}
</div>
<footer></footer>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous">
</script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/app/chart.html
{% extends "app/base.html" %}
{% load static %}
{% block main %}
    <main class="container">
        <div>
            <label for="daterange">Date Range</label>
            <input type="text" id="daterange" name="daterange" value="01/01/2019 - 02/01/2020" />

            <canvas id="myChart"></canvas>
        </div>
    </main>
{% endblock %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>
        $(document).ready(function () {

            let DrawChart = function (data){
                var ctx = document.getElementById('myChart');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: data
                });
            };

            let GetChartData = function (d1, d2) {
                $.ajax({
                    url: '/api/chart/' + d1 + '/' + d2 + '/',
                    method: 'GET',
                    dataType: 'json',
                    success: function (d) {

                        let v = [];
                        let labels = [];
                        $.each(d.results, function( index, value ) {
                            labels.push(value['last_modified_date']);
                            v.push(value['cve_count']);
                        });

                        let data = {
                            labels: labels,
                            datasets: [{
                                label: '# of CVEs modified',
                                data: v,
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                ],
                                borderWidth: 1
                            }]
                        };
                        console.log("data");
                        console.log(data);
                        DrawChart(data);
                    }
                });
            };

            GetChartData('2019-01-01', '2020-02-01');

             $('input[name="daterange"]').daterangepicker({
                opens: 'left'
              }, function(start, end, label) {
                 GetChartData(start.format('YYYY-MM-DD'), end.format('YYYY-MM-DD'));
              });

        });
</script>
{% endblock %}

app/templates/app/detail.html
{% extends "app/base.html" %}
{% load static %}
{% block main %}
    <main class="container">
        <div class="clearfix">
            <ul class="list-inline float-right">
              <li class="list-inline-item">
                  <a href="{% url 'app:download' id=cve.cve_id %}">Download</a>
              </li>
              <li class="list-inline-item">
                  <a href="{% url 'app:index' %}">Back</a>
              </li>
            </ul>
        </div>
        <h3>
            {{ cve.cve_id }}
        </h3>
        <div class="clearfix">
            <ul class="list-inline float-right">
              <li class="list-inline-item"><strong>Published:</strong> {{ cve.published_date }}</li>
              <li class="list-inline-item"><strong>Last Modified:</strong> {{ cve.last_modified_date }}</li>
            </ul>
        </div>
        <p class="jumbotron">
            {{ cve.summary }}
        </p>
        <h3>Severity</h3>
        {% if cve.cvss_v3_base_score %}
            <h5>CVSS V3.X</h5>
            <p class="lead">
                <strong>Base Score:</strong> <span>{{ cve.cvss_v3_base_score }}</span><br>
                <strong>Severity:</strong> <span>{{ cve.cvss_v3_severity }}</span><br>
                <strong>Vector:</strong> <span>{{ cve.cvss_v3_vector_string }}</span><br>
            </p>
        {% endif %}
        {% if cve.cvss_v2_base_score %}
            <h5>CVSS V2.0</h5>
            <p class="lead">
                <strong>Base Score:</strong> <span>{{ cve.cvss_v2_base_score }}</span><br>
                <strong>Severity:</strong> <span>{{ cve.cvss_v2_severity }}</span><br>
                <strong>Vector:</strong> <span>{{ cve.cvss_v2_vector_string }}</span><br>
            </p>
        {% endif %}
        <h3>References</h3>
        {% if cve.reference_set.all %}
            <ul>

                {% for ref in cve.reference_set.all %}
                    <li>
                        <a href="{{ ref.url }}" target="_blank">{{ ref.url }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>N/A</p>
        {% endif %}
        <h3>Affected Software</h3>
        {% if cve.affected_products > 0 %}
            <ul>
                {% for software in cve.affectedproduct_set.all %}
                    <li>
                        {% if software.vulnerable %}Vulnerable: {% endif %}
                        {{ software.uri }}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>N/A</p>
        {% endif %}
    </main>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}
{% block main %}
    <main class="container-fluid">
        <div class="col-auto pull-right">
            <input type="text" id="cveSearch">
            <button type="button" id="cveSearchSubmit" class="btn btn-primary">Search</button>
        </div>
        <div class="clearfix"></div>
        <table id="cve_table" class="table table-condensed table-striped table-hover">
            <thead>
            <tr>
                <th>CVE ID</th>
                <th>Summary</th>
                <th>Published</th>
                <th>Last Modified</th>
                <th>Affected Products</th>
                <th>CVSS Severity</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </main>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            var cveTable = $('#cve_table').DataTable({
                "iDisplayLength": 100,
                "deferRender": true,
                "dom": '<"top"flp<"clear">>rt<"bottom"ifp<"clear">>',
                "processing": true,
                "serverSide": true,
                "searching": false,
                "dataSrc": "results",
                "order": [
                    [0, "asc"]
                ],
                "ajax": {
                    "url": "/api/cve/",
                    "data": function (data) {
                        data.page = data.draw;
                        delete data.draw;
                        data.limit = data.length;
                        delete data.length;
                        data.offset = data.start;
                        data.search = $('#cveSearch').val();
                        var ordering = data.columns[data.order[0].column].data;
                        if (data.order[0].dir === 'asc') {
                            data.ordering = ordering;
                        } else {
                            data.ordering = "-" + ordering;
                        }
                        delete data.start;
                        return data;
                    },
                    "dataFilter": function (data) {
                        var json = jQuery.parseJSON(data);
                        json.recordsTotal = json.count;
                        json.recordsFiltered = json.count;
                        json.data = json.results;
                        delete json.results;
                        return JSON.stringify(json);
                    }
                },
                "columns": [
                    { "data": "cve_id",
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a href='/app/cves/detail/"+oData.cve_id +"'>"+ oData.cve_id +"</a>");
                        }
                    },
                    {
                        "data": "summary", "orderable": false,
                        "render": function (data, type, row) {
                            if(data.length > 50)
                                return data.substring(0, 50) + "...";
                            else
                                return data;
                        }
                    },
                    {
                        "data": "published_date"
                    },
                    {
                        "data": "last_modified_date"
                    },
                    {
                        "data": "affected_products", "className": 'dt-body-right'
                    },
                    {
                        "data": "cvss_v2_base_score", "className": 'dt-body-right',
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            if(oData.cvss_v2_base_score != null) {
                                let c = 'info';
                                const s = oData.cvss_v2_base_score;
                                switch(true){
                                    case s < 4.0:
                                        c = 'success';
                                        break;
                                    case s < 7:
                                        c = 'warning';
                                        break;
                                    case s < 11:
                                        c = 'danger';
                                        break;
                                }
                                $(nTd).html(oData.cvss_v2_base_score + " <span class='badge badge-"+ c +"'>" +
                                    oData.cvss_v2_severity + "</span>");
                            }
                        }

                    },

                ]
            });

            $('#cveSearchSubmit').click(function (e) {
                cveTable.draw();
            });
        });
    </script>
{% endblock %}